`default_nettype none

module sar_adc_clean (

    input  wire       clk,
    input  wire       rst_n,

    // Shared signals generated by the Tiny Tapeout top level
    input  wire       adc_tick,
    input  wire       comp_sync,

    output reg        sample_sw,
    output reg  [3:0] dac,
    output reg  [3:0] result_code,
    output wire [2:0] state_out
);

    //============================================================
    // SAR ADC STATE DEFINITIONS
    //============================================================

    localparam [2:0]
        SAMPLE    = 3'd0,
        HOLD      = 3'd1,
        SET_BIT   = 3'd2,
        WAIT_DAC  = 3'd3,
        READ_COMP = 3'd4,
        DONE      = 3'd5;

    reg [2:0] state;
    reg [1:0] bit_index;

    parameter COMP_HIGH_MEANS_KEEP = 1'b1;

    assign state_out = state;


    //============================================================
    // CLEAN SAR ADC CONTROL LOGIC
    //============================================================

    always @(posedge clk) begin
        if (!rst_n) begin
            state     <= SAMPLE;
            sample_sw <= 1'b1;
            dac         <= 4'b0000;
            result_code <= 4'b0000;
            bit_index   <= 2'd3;
        end
        else if (adc_tick) begin
            case (state)

                SAMPLE: begin
                    sample_sw <= 1'b1;
                    dac       <= 4'b0000;
                    bit_index <= 2'd3;
                    state     <= HOLD;
                end

                HOLD: begin
                    sample_sw <= 1'b0;
                    bit_index <= 2'd3;
                    state     <= SET_BIT;
                end

                SET_BIT: begin
                    dac[bit_index] <= 1'b1;
                    state          <= WAIT_DAC;
                end

                WAIT_DAC: begin
                    state <= READ_COMP;
                end

                READ_COMP: begin
                    if (COMP_HIGH_MEANS_KEEP) begin
                        if (!comp_sync)
                            dac[bit_index] <= 1'b0;
                    end
                    else begin
                        if (comp_sync)
                            dac[bit_index] <= 1'b0;
                    end

                    if (bit_index == 2'd0) begin
                        state <= DONE;
                    end
                    else begin
                        bit_index <= bit_index - 1'b1;
                        state     <= SET_BIT;
                    end
                end

                DONE: begin
                    // Preserve the completed conversion while the next
                    // SAR conversion changes the live DAC trial bits.
                    result_code <= dac;

                    sample_sw <= 1'b1;
                    bit_index <= 2'd3;
                    state     <= SAMPLE;
                end

                default: begin
                    state       <= SAMPLE;
                    sample_sw   <= 1'b1;
                    dac         <= 4'b0000;
                    result_code <= 4'b0000;
                    bit_index   <= 2'd3;
                end

            endcase
        end
    end

endmodule

`default_nettype wire
